use crate::{
    event::{
        Data,
        InfoError,
    },
    prelude::*,
};

pub(crate) async fn info(transaction: &mut Transaction<'_, Postgres>, data: &Data<'_>) -> Result<Option<RawHtml<String>>, InfoError> {
    Ok(match &*data.event {
        "2" => Some(html! {
            article {
                p {
                    : "This is the 2nd season of the Tournament of Truth, organized by ";
                    : English.join_html_opt(data.organizers(transaction).await?);
                    : ". See ";
                    a(href = "https://docs.google.com/document/d/1YNCm4XUCeWlz9UHPz5lwTIRUVasnAIjP8aXC7r5djWc/edit") : "the official document";
                    : " for details.";
                }
            }
        }),
        _ => None,
    })
}

pub(crate) fn s2_settings() -> seed::Settings {
    collect![
        format!("password_lock") => json!(true),
        format!("trials") => json!(0),
        format!("shuffle_ganon_bosskey") => json!("remove"),
        format!("open_forest") => json!("closed_deku"),
        format!("open_kakariko") => json!("open"),
        format!("open_door_of_time") => json!("open"),
        format!("gerudo_fortress") => json!("fast"),
        format!("starting_age") => json!("random"),
        format!("free_bombchu_drops") => json!(false),
        format!("shuffle_child_trade") => json!([
            "Keaton Mask",
            "Skull Mask",
            "Spooky Mask",
            "Bunny Hood",
        ]),
        format!("adult_trade_start") => json!([
            "Prescription",
            "Eyeball Frog",
            "Eyedrops",
            "Claim Check",
        ]),
        format!("shuffle_mapcompass") => json!("startwith"),
        format!("disabled_locations") => json!([
            "Deku Theater Skull Mask",
            "Market Mask Shop Item 5",
            "Market Mask Shop Item 6",
            "Market Mask Shop Item 7",
            "Market Mask Shop Item 8",
        ]),
        format!("allowed_tricks") => json!([
            "logic_grottos_without_agony",
            "logic_fewer_tunic_requirements",
            "logic_rusted_switches",
            "logic_man_on_roof",
            "logic_windmill_poh",
            "logic_crater_bean_poh_with_hovers",
            "logic_dc_jump",
            "logic_lens_botw",
            "logic_child_deadhand",
            "logic_forest_vines",
            "logic_lens_shadow",
            "logic_lens_shadow_platform",
            "logic_lens_bongo",
            "logic_lens_spirit",
            "logic_lens_gtg",
            "logic_lens_castle",
        ]),
        format!("starting_equipment") => json!([
            "deku_shield",
        ]),
        format!("starting_inventory") => json!([
            "ocarina",
            "farores_wind",
            "zeldas_letter",
            "keaton_mask",
            "skull_mask",
            "spooky_mask",
            "bunny_hood",
        ]),
        format!("start_with_consumables") => json!(true),
        format!("skip_reward_from_rauru") => json!(true),
        format!("no_escape_sequence") => json!(true),
        format!("no_guard_stealth") => json!(true),
        format!("no_epona_race") => json!(true),
        format!("skip_some_minigame_phases") => json!(true),
        format!("scarecrow_behavior") => json!("fast"),
        format!("ruto_already_f1_jabu") => json!(true),
        format!("fast_shadow_boat") => json!(true),
        format!("chicken_count") => json!(3),
        format!("big_poe_count") => json!(1),
        format!("hint_dist_user") => json!({
            "name":                  "FR",
            "gui_name":              "FR",
            "description":           "hihi",
            "add_locations":         [
                { "location": "Graveyard Dampe Gravedigging Tour", "types": ["sometimes"] },
                { "location": "Deku Theater Skull Mask", "types": ["always"] },
                { "location": "Sheik in Kakariko", "types": ["always"] },
            ],
            "remove_locations":      [
                {"location": "Sheik in Crater", "types": ["sometimes"]},
                {"location": "Song from Royal Familys Tomb", "types": ["sometimes"]},
                {"location": "Sheik in Forest", "types": ["sometimes"]},
                {"location": "Sheik at Temple", "types": ["sometimes"]},
                {"location": "Sheik at Colossus", "types": ["sometimes"]},
                {"location": "GF HBA 1500 Points", "types": ["sometimes"]},
                {"location": "GC Maze Left Chest", "types": ["sometimes"]},
                {"location": "GV Chest", "types": ["sometimes"]},
                {"location": "Graveyard Royal Familys Tomb Chest", "types": ["sometimes"]},
                {"location": "GC Pot Freestanding PoH", "types": ["sometimes"]},
                {"location": "LH Lab Dive", "types": ["sometimes"]},
                {"location": "Water Temple Boss Key Chest", "types": ["sometimes"]},
                {"location": "Gerudo Training Ground Maze Path Final Chest", "types": ["sometimes"]},
                {"location": "Spirit Temple Silver Gauntlets Chest", "types": ["sometimes"]},
                {"location": "Spirit Temple Mirror Shield Chest", "types": ["sometimes"]},
                {"location": "Shadow Temple Freestanding Key", "types": ["sometimes"]},
                {"location": "Ice Cavern Iron Boots Chest", "types": ["sometimes"]},
                {"location": "Ganons Castle Shadow Trial Golden Gauntlets Chest", "types": ["sometimes"]},
                {"location": "Deku Theater Mask of Truth", "types": ["always"]},
                { "location": "Graveyard Dampe Race Rewards", "types": ["dual"] },
                { "location": "Graveyard Royal Family Tomb Contents", "types": ["dual"] },
                { "location": "Fire Temple Lower Loop", "types": ["dual"] },
                { "location": "ZR Frogs Rewards", "types": ["dual"] },
                { "location": "Deku Theater Rewards", "types": ["dual"] },
                { "location": "Ice Cavern Final Room", "types": ["dual"] },
                { "location": "Spirit Temple Child Lower", "types": ["dual"] },
                { "location": "Spirit Temple Child Top", "types": ["dual"] },
                { "location": "Spirit Temple Adult Lower", "types": ["dual"] },
                { "location": "Spirit Temple Colossus Hands", "types": ["dual"] },
                { "location": "Shadow Temple Invisible Blades Chests", "types": ["dual"] },
                { "location": "Shadow Temple Spike Walls Room", "types": ["dual"] },
                { "location": "Ganons Castle Spirit Trial Chests", "types": ["dual"] },
                {"location": "Inside Ganon's Castle", "types": ["barren"]},
            ],
            "add_items":             [],
            "remove_items":          [
                { "item": "Zeldas Lullaby", "types": ["goal"] },
                { "item": "Light Arrows", "types": ["goal"] },
            ],
            "dungeons_woth_limit":   2,
            "dungeons_barren_limit": 1,
            "one_hint_per_goal":     true,
            "named_items_required":  true,
            "vague_named_items":     false,
            "distribution":          {
                "trial":           {"order": 1, "weight": 0.0, "fixed":   0, "copies": 2},
                "entrance_always": {"order": 2, "weight": 0.0, "fixed":   0, "copies": 2},
                "always":          {"order": 3, "weight": 0.0, "fixed":   0, "copies": 3, "remove_stones": [
                    "ToT (Left)",
                    "ToT (Left-Center)",
                    "ToT (Right-Center)",
                    "ToT (Right)",
                    "HF (Cow Grotto)",
                    "HC (Storms Grotto)",
                    "LH (Southeast Corner)",
                    "LH (Southwest Corner)",
                ]},
                "junk":            {"order": 4, "weight": 0.0, "fixed":   4, "copies": 1, "priority_stones": [
                    "HF (Cow Grotto)",
                    "HC (Storms Grotto)",
                    "LH (Southeast Corner)",
                    "LH (Southwest Corner)",
                ]},
                "barren":          {"order": 5, "weight": 0.0, "fixed":   4, "copies": 1, "priority_stones": [
                    "ToT (Left)",
                    "ToT (Left-Center)",
                    "ToT (Right-Center)",
                    "ToT (Right)",
                ]},
                "goal":            {"order": 6, "weight": 0.0, "fixed":   5, "copies": 2},
                "dual":            {"order": 7, "weight": 0.0, "fixed":   2, "copies": 2},
                "sometimes":       {"order": 8, "weight": 0.0, "fixed": 100, "copies": 2},
                "woth":            {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "entrance":        {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "random":          {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "item":            {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "song":            {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "overworld":       {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "dungeon":         {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
                "named-item":      {"order": 0, "weight": 0.0, "fixed":   0, "copies": 2},
            },
        }),
        format!("misc_hints") => json!([
            "altar",
            "ganondorf",
            "warp_songs_and_owls",
            "10_skulltulas",
            "20_skulltulas",
            "30_skulltulas",
            "40_skulltulas",
            "50_skulltulas",
            "mask_of_truth",
        ]),
        format!("correct_chest_appearances") => json!("both"),
        format!("blue_fire_arrows") => json!(true),
        format!("tcg_requires_lens") => json!(true),
        format!("junk_ice_traps") => json!("off"),
        format!("ice_trap_appearance") => json!("anything"),
    ]
}
